### ISSUE TITLE
property duplication

### ISSUE THREAD

**Issue by freeman-lab** [carbonplan/minimaps#5]
This one is a bit weird. When rendering multiple maps that use the same projection, if projection-related props are set differently between the maps, the settings on one of them seems to override the other!

To reproduce, if we run the following

```jsx
<>
    <Box sx={{ width: '50%' }}>
      <Minimap projection={naturalEarth1} scale={3}>
        <Path
          stroke={'white'}
          source={'https://cdn.jsdelivr.net/npm/world-atlas@2/land-50m.json'}
          feature={'land'}
        />
        <Graticule stroke={'white'} />
        <Sphere fill={'white'} />
        <Raster
          source={
            'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Blue_Marble_2002.png/2880px-Blue_Marble_2002.png'
          }
          format={'rgb'}
          transpose
        />
      </Minimap>
    </Box>
    <Box sx={{ width: '50%' }}>
      <Minimap projection={naturalEarth1} scale={3}>
        <Path
          stroke={'white'}
          source={'https://cdn.jsdelivr.net/npm/world-atlas@2/land-50m.json'}
          feature={'land'}
        />
        <Graticule stroke={'white'} />
        <Sphere fill={'white'} />
        <Raster
          source={
            'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Blue_Marble_2002.png/2880px-Blue_Marble_2002.png'
          }
          format={'rgb'}
          transpose
        />
      </Minimap>
    </Box>
    </>
```

We get two zoomed in (`scale` of `3`) maps, as expected:
<img width="719" alt="CleanShot 2022-03-07 at 12 37 34@2x" src="https://user-images.githubusercontent.com/3387500/157097108-6715400a-69f6-439e-9d07-2e5aba653a3a.png">

But if we set the scale on the second one to `1`, we get this:
<img width="718" alt="CleanShot 2022-03-07 at 12 37 43@2x" src="https://user-images.githubusercontent.com/3387500/157097245-bcd75199-01c6-4a88-88b4-6b19ade6cbb5.png">

The second map is rendered correctly with a scale of `1`, but the first map is rendered, oddly, with a `scale` of `3` being applied to the `Raster` but a `scale` of `1` being used on the `Path` and `Sphere`. Because we are passing the projection itself, I _think_ the setting of scale on the second must be somehow mutating the first. But we're cloning the `projection` object upon construction in `Minimaps` (I think!), so, I don't see how that would happen. Definitely possible there's something here about mutation I don't understand or have messed up.

I'm a little stumped, so it'd be great if @katamartin wanted to poke around at this one!

**Comment by katamartin** [comment]
Interesting!

It looks like the way we're cloning `projection`s will not be sufficient. When we reference `Object.assign({}, projection)` [here](https://github.com/carbonplan/minimaps/blob/main/src/minimap.js#L40), we are still creating opportunities for multiple `Minimap`s to access and same underlying projection _functions_, which mutate variables which are not accessed via the `projection` object but via [closure](https://github.com/d3/d3-geo/blob/main/src/projection/index.js#L63-L78).

I think the simplest fix would be to update the `minimaps/projections` interface to export _functions_ instead of projection singletons.

e.g. for `naturalEarth1`:
```js
export default function () {
  const projection = geoNaturalEarth1().precision(0.1)
  projection.glsl = { func: naturalEarth1Invert, name: 'naturalEarth1Invert' }
  projection.id = 'naturalEarth1'
  return projection
}
```

This works as expected when I change the first minimap to have `scale={1}`:
<img width="432" alt="Screen Shot 2022-03-07 at 3 16 16 PM" src="https://user-images.githubusercontent.com/12436887/157134469-399c00d3-9a83-418a-8af1-532a85bcacbe.png">

but creates a new spooky issue when the setting the second minimap to `scale={1}`:
<img width="457" alt="Screen Shot 2022-03-07 at 3 16 04 PM" src="https://user-images.githubusercontent.com/12436887/157134438-f8616b70-a151-45fe-878d-d501aadf47ec.png">

**Comment by katamartin** [comment]
This seemed like it could be related to issues that I'm seeing in my testing:

![scaling2](https://user-images.githubusercontent.com/12436887/157567000-58c2e735-4938-47c5-b10e-a4b72380b580.gif)

1. The `Raster` layer sometimes is not drawn on initial render
2. An _already_ mounted `Raster` layer handles resizing just fine, but a _newly_ mounted `Raster` layer does not have the expected scale

I'm running into these both in `1.0.0-develop.2` and locally testing with [a change](https://github.com/carbonplan/minimaps/commit/3d6958f7223c7c57f43644e9c7693c453530a7a9) that makes this change to the `projection` exports, so having a hard time pinpointing what could be the culprit.

**Comment by freeman-lab** [comment]
This has been resolved in recent commits!
